#ifndef _CEREBOTBOARDS_H_
#define _CEREBOTBOARDS_H_
#include <peripheral/ports.h>
#include <stdint.h>

#include <stdint.h>

//#if defined __CEREBOT32MX4__
	//Pmod pin connector to MCU port mappings
    #define IO_PORT_JA01    IOPORT_E
    #define IO_PORT_JA02    IOPORT_E
    #define IO_PORT_JA03    IOPORT_E
    #define IO_PORT_JA04    IOPORT_E
    #define IO_PORT_JA07    IOPORT_E
    #define IO_PORT_JA08    IOPORT_E
    #define IO_PORT_JA09    IOPORT_E
    #define IO_PORT_JA10    IOPORT_E
    #define IO_PORT_JB01    IOPORT_G
    #define IO_PORT_JB02    IOPORT_G
    #define IO_PORT_JB03    IOPORT_G
    #define IO_PORT_JB04    IOPORT_G
    #define IO_PORT_JB07    IOPORT_B
    #define IO_PORT_JB08    IOPORT_D
    #define IO_PORT_JB09    IOPORT_D
    #define IO_PORT_JB10    IOPORT_B
    #define IO_PORT_JC01    IOPORT_G
    #define IO_PORT_JC02    IOPORT_G
    #define IO_PORT_JC03    IOPORT_G
    #define IO_PORT_JC04    IOPORT_G
    #define IO_PORT_JC07    IOPORT_G
    #define IO_PORT_JC08    IOPORT_G
    #define IO_PORT_JC09    IOPORT_F
    #define IO_PORT_JC10    IOPORT_F
    #define IO_PORT_JD01    IOPORT_D
    #define IO_PORT_JD02    IOPORT_D
    #define IO_PORT_JD03    IOPORT_D
    #define IO_PORT_JD04    IOPORT_C
    #define IO_PORT_JD07    IOPORT_D
    #define IO_PORT_JD08    IOPORT_D
    #define IO_PORT_JD09    IOPORT_D
    #define IO_PORT_JD10    IOPORT_C
    #define IO_PORT_JE01    IOPORT_D
    #define IO_PORT_JE02    IOPORT_D
    #define IO_PORT_JE03    IOPORT_F
    #define IO_PORT_JE04    IOPORT_F
    #define IO_PORT_JE07    IOPORT_D
    #define IO_PORT_JE08    IOPORT_D
    #define IO_PORT_JE09    IOPORT_D
    #define IO_PORT_JE10    IOPORT_A
    #define IO_PORT_JF01    IOPORT_A
    #define IO_PORT_JF02    IOPORT_A
    #define IO_PORT_JF03    IOPORT_A
    #define IO_PORT_JF04    IOPORT_A
    #define IO_PORT_JH01    IOPORT_F
    #define IO_PORT_JH02    IOPORT_F
    #define IO_PORT_JH03    IOPORT_F
    #define IO_PORT_JH04    IOPORT_F
    #define IO_PORT_JH07    IOPORT_E
    #define IO_PORT_JH08    IOPORT_D
    #define IO_PORT_JH09    IOPORT_D
    #define IO_PORT_JH10    IOPORT_E
    #define IO_PORT_JJ01    IOPORT_B
    #define IO_PORT_JJ02    IOPORT_B
    #define IO_PORT_JJ03    IOPORT_B
    #define IO_PORT_JJ04    IOPORT_B
    #define IO_PORT_JJ07    IOPORT_B
    #define IO_PORT_JJ08    IOPORT_B
    #define IO_PORT_JJ09    IOPORT_B
    #define IO_PORT_JJ10    IOPORT_B
    #define IO_PORT_JK01    IOPORT_B
    #define IO_PORT_JK02    IOPORT_B
    #define IO_PORT_JK03    IOPORT_B
    #define IO_PORT_JK04    IOPORT_B
    #define IO_PORT_JK07    IOPORT_A
    #define IO_PORT_JK08    IOPORT_A
    #define IO_PORT_JK09    IOPORT_D
    #define IO_PORT_JK10    IOPORT_C

	//Pmod PIN connector pin to MCU port bit mappings
    #define PIN_JA01    BIT_0
    #define PIN_JA02    BIT_1
    #define PIN_JA03    BIT_2
    #define PIN_JA04    BIT_3
    #define PIN_JA07    BIT_4
    #define PIN_JA08    BIT_5
    #define PIN_JA09    BIT_6
    #define PIN_JA10    BIT_7
    #define PIN_JB01    BIT_9
    #define PIN_JB02    BIT_8
    #define PIN_JB03    BIT_7
    #define PIN_JB04    BIT_6
    #define PIN_JB07    BIT_15
    #define PIN_JB08    BIT_5
    #define PIN_JB09    BIT_4
    #define PIN_JB10    BIT_14
    #define PIN_JC01    BIT_12
    #define PIN_JC02    BIT_13
    #define PIN_JC03    BIT_14
    #define PIN_JC04    BIT_15
    #define PIN_JC07    BIT_0
    #define PIN_JC08    BIT_1
    #define PIN_JC09    BIT_0
    #define PIN_JC10    BIT_1
    #define PIN_JD01    BIT_7
    #define PIN_JD02    BIT_1
    #define PIN_JD03    BIT_9
    #define PIN_JD04    BIT_1
    #define PIN_JD07    BIT_6
    #define PIN_JD08    BIT_2
    #define PIN_JD09    BIT_10
    #define PIN_JD10    BIT_2
    #define PIN_JE01    BIT_14
    #define PIN_JE02    BIT_15
    #define PIN_JE03    BIT_2
    #define PIN_JE04    BIT_8
    #define PIN_JE07    BIT_13
    #define PIN_JE08    BIT_3
    #define PIN_JE09    BIT_11
    #define PIN_JE10    BIT_3
    #define PIN_JF01    BIT_2
    #define PIN_JF02    BIT_3
    #define PIN_JF03    BIT_6
    #define PIN_JF04    BIT_7
    #define PIN_JH01    BIT_12
    #define PIN_JH02    BIT_13
    #define PIN_JH03    BIT_4
    #define PIN_JH04    BIT_5
    #define PIN_JH07    BIT_8
    #define PIN_JH08    BIT_0
    #define PIN_JH09    BIT_8
    #define PIN_JH10    BIT_9
    #define PIN_JJ01    BIT_0
    #define PIN_JJ02    BIT_1
    #define PIN_JJ03    BIT_2
    #define PIN_JJ04    BIT_3
    #define PIN_JJ07    BIT_4
    #define PIN_JJ08    BIT_5
    #define PIN_JJ09    BIT_8
    #define PIN_JJ10    BIT_9
    #define PIN_JK01    BIT_10
    #define PIN_JK02    BIT_11
    #define PIN_JK03    BIT_12
    #define PIN_JK04    BIT_13
    #define PIN_JK07    BIT_9
    #define PIN_JK08    BIT_10
    #define PIN_JK09    BIT_12
    #define PIN_JK10    BIT_4



#endif
